User creation
mateuscelio/todddo pull request #20
Opened 2023-03-31 17:27 UTC by mateuscelio

2023-04-05 16:39 UTC, v-malexandre-godaddy commented on app/controllers/users/sessions_controller.rb
> +    end
Faltou remover?

2023-04-05 16:43 UTC, v-malexandre-godaddy commented on app/models/user/infrastructure/active_record_user_repository.rb
> +                               updated_at: user.updated_at)
Temos uma repetição dessa lógica de conversão de um model do Rails pra uma entidade do domínio (no `.find` e no `.last`). Nesse caso podemos adicionar um data mapper na camada de infraestrutura responsável por isso, pra poder fazer algo como `::User::Infrastructure::ActiveRecordUserMapper.to_entity(user_record)`.

O que acha?

2023-04-05 16:44 UTC, v-malexandre-godaddy requested changes
Deixei dois comentários, mas fora isso tá show. :clap:

2023-04-05 16:58 UTC, mateuscelio commented on app/controllers/users/sessions_controller.rb
> +    end
Na verdade  esse controller nem deveria existir hehehe

2023-04-05 17:26 UTC, mateuscelio commented on app/models/user/infrastructure/active_record_user_repository.rb
> +                               updated_at: user.updated_at)
Faz sentido, ainda nao havia adicionado o conceito de data mappers ao projeto, vejo é um bom caso para dar inicio.

2023-04-10 14:12 UTC, marcelobalexandre approved these changes

2023-04-10 20:31 UTC, merged