Add task creation controller
mateuscelio/todddo pull request #5
Opened 2022-10-20 12:59 UTC by mateuscelio

2022-10-23 21:23 UTC, marcelobalexandre commented on Gemfile
> +gem 'shoulda-matchers', '~> 5.2'
Como essa gem é utilizada apenas nos testes, o que acha de mover ela pra dentro do grupo `:test`?

2022-10-23 21:29 UTC, marcelobalexandre commented on app/controllers/application_controller.rb
> +  def record_invalid(exception)
O que acha de alterar esse método para `private`? Qual seria o benefício de alterar ele pra privado?

2022-10-23 21:31 UTC, marcelobalexandre commented on app/controllers/application_controller.rb
> +    }, status: :unprocessable_entity
Gostei que você centralizou o tratamento para erros de validação aqui.

O que acha de adicionar um serializer pra isso?

2022-10-23 21:33 UTC, marcelobalexandre commented on spec/factories/tasks.rb
> +    due_at { '2022-09-29 12:54:59 UTC' }
Não podemos ter problemas com a validação `due_at_cannot_be_in_the_past` aqui?

2022-10-23 21:34 UTC, marcelobalexandre commented on spec/factories/tasks.rb
> +    due_at { '2022-09-29 12:54:59 UTC' }
O que acha de adicionar o `Faker` para popularmos esses atributos?

2022-10-23 21:44 UTC, marcelobalexandre commented on spec/models/task_spec.rb
> +      it 'raises error' do
Na verdade o `save` não vai disparar um erro, e sim retornar `false` e adicionar os erros em `errors`, certo?

Nesse caso, o que acha de alterar o texto para algo como `validates that due_at cannot be in the past` removendo  o `describe`? Estou sugerindo dessa forma pra ficar parecido com o que o `shoulda-matchers` faz, mas se preferir pode usar outro padrão.

2022-10-23 21:47 UTC, marcelobalexandre commented on spec/models/task_spec.rb
> +  context 'validations' do
Minor, eu usaria `describe` para enfatizar que estamos "descrevendo" as validações, normalmente eu uso `context` para definir os diferentes cenários possíveis.

2022-10-23 21:50 UTC, marcelobalexandre requested changes
Adicionei alguns comentários.

Rola configurar um `docker-compose´ pra facilitar rodar o projeto? :D

2022-10-27 10:38 UTC, mateuscelio commented on app/controllers/application_controller.rb
> +  def record_invalid(exception)
A vantagem seria isolar este comportamento das classes que herdam `AplicationController`

2022-10-27 11:44 UTC, mateuscelio commented on app/controllers/application_controller.rb
> +    }, status: :unprocessable_entity
Criei uma classe separada para ser responsavel pela serialização. Veja se é assim que havias pensado em fazer

2022-10-27 12:21 UTC, marcelobalexandre commented on app/controllers/application_controller.rb
> +  def record_invalid(exception)
Isso mesmo, dessa forma evitamos algum acoplamento indevido desse método, a ideia é que quanto menos métodos públicos um objeto tem menor a quantidade de acoplamentos possíveis a ele.

2022-10-27 12:22 UTC, marcelobalexandre commented on spec/models/task_spec.rb
> +      task = build(:task, due_at: 1.day.ago)
Bom uso do `build` pra evitar salvar o dado no banco sem necessidade. 👏

2022-10-27 12:29 UTC, marcelobalexandre commented on app/serializers/api/v1/error_serializer.rb
> +            details: @error[:exception].record.errors.full_messages
Eu sempre prefiro adicionar `attr_reader` privado pra esses casos pra podermos chamar sem o `@`, a ideia é que usando o `error` sem o `@` evitaria a necessidade de alterar essas linhas caso um dia seja necessário alterar de um atributo para um método `#error`, já que ambos o `attr_reader` e o método seriam chamados sem o `@`.

Mas considero que isso é algo mais de gosto pessoal, então não precisa alterar se não quiser.

2022-10-27 12:30 UTC, marcelobalexandre commented on config/routes.rb
> +      resources :tasks, only: %i[create]
Bom uso do `only` pra evitar a criação de rotas desnecessárias. 👏

2022-10-27 12:41 UTC, marcelobalexandre commented on app/controllers/api/v1/tasks_controller.rb
> +        params.permit(:name, :description, :due_at)
Tá rolando esse erro aqui:
```
Unpermitted parameter: :task. Context: { controller: Api::V1::TasksController, action: create, request: #<ActionDispatch::Request:0x00007f7d2aeb7db0>, params: {"name"=>"Do something new", "description"=>"Description", "controller"=>"api/v1/tasks", "action"=>"create", "task"=>{"name"=>"Do something new", "description"=>"Description"}} }
```

```suggestion
        params.require(:task).permit(:name, :description, :due_at)
```

2022-10-27 12:43 UTC, marcelobalexandre requested changes
https://github.com/mateuscelio/todddo/pull/5#discussion_r1006820993

2022-12-14 21:25 UTC, merged